CREATE_PARKING_LOT = 'create_parking_lot'
PARK = 'park'
LEAVE = 'leave'
PARKING_LOT_STATUS = 'status'
SLOT_NUMBERS_OF_CARS_WITH_COLOR = 'slot_numbers_for_cars_with_colour'
REGISTRATION_NUMBERS_OF_CARS_WITH_COLOR = 'registration_numbers_for_cars_with_colour'
SLOT_NUMBERS_OF_CARS_WITH_REGISTRATION = 'slot_number_for_registration_number'

ALL_COMMANDS = [CREATE_PARKING_LOT, PARK, LEAVE, PARKING_LOT_STATUS, SLOT_NUMBERS_OF_CARS_WITH_COLOR,
                SLOT_NUMBERS_OF_CARS_WITH_REGISTRATION, REGISTRATION_NUMBERS_OF_CARS_WITH_COLOR]
